-- MySQL Script generated by MySQL Workbench
-- 03/27/17 19:42:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `smasy_pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_pais` ;

CREATE TABLE IF NOT EXISTS `smasy_pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(10) NULL,
  `nome` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_estado` ;

CREATE TABLE IF NOT EXISTS `smasy_estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(10) NULL,
  `nome` VARCHAR(50) NULL,
  `pais` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais_idx` (`pais` ASC),
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `smasy_pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_cidade` ;

CREATE TABLE IF NOT EXISTS `smasy_cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NULL,
  `nome` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `smasy_estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_imagem` ;

CREATE TABLE IF NOT EXISTS `smasy_imagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `type` VARCHAR(10) NULL,
  `caminho` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_pessoa` ;

CREATE TABLE IF NOT EXISTS `smasy_pessoa` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dtnascimento` DATE NOT NULL,
  `estadocivil` INT NULL,
  `sexo` CHAR(1) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` INT NULL,
  `cidade` INT NULL,
  `cep` INT NULL,
  `pais` INT NULL,
  `cpf` INT NULL,
  `idimagem` INT NULL,
  `telefone1` VARCHAR(45) NULL,
  `telefone2` VARCHAR(45) NULL,
  `telefone3` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `ufcartident` INT NULL,
  `orgemissorident` VARCHAR(45) NULL,
  `dtemissaoident` VARCHAR(45) NULL,
  `naturalidade` INT NULL,
  `estadonatal` INT NULL,
  `email` VARCHAR(45) NULL,
  `reccreatedby` INT NOT NULL,
  `reccreatedon` DATETIME NOT NULL,
  `recmodifiedby` INT NULL,
  `recmodifiedon` DATETIME NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pessoa_estado_idx` (`estado` ASC),
  INDEX `fk_pessoa_cidade_idx` (`cidade` ASC),
  INDEX `fk_pessoa_imagem_idx` (`idimagem` ASC),
  INDEX `fk_pessoa_pais_idx` (`pais` ASC),
  CONSTRAINT `fk_pessoa_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `smasy_estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_cidade`
    FOREIGN KEY (`cidade`)
    REFERENCES `smasy_cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_imagem`
    FOREIGN KEY (`idimagem`)
    REFERENCES `smasy_imagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `smasy_pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_aluno` ;

CREATE TABLE IF NOT EXISTS `smasy_aluno` (
  `ra` INT NOT NULL AUTO_INCREMENT,
  `codpessoa` INT NOT NULL,
  `anoingresso` VARCHAR(10) NULL,
  `responsavel` INT NULL,
  `reccreatedby` INT NOT NULL,
  `reccreatedon` DATETIME NOT NULL,
  `recmodifiedby` INT NULL,
  `recmodifiedon` DATETIME NULL,
  PRIMARY KEY (`ra`),
  INDEX `fk_aluno_pessoa_idx` (`codpessoa` ASC),
  INDEX `fk_aluno_pessoa_respo_idx` (`responsavel` ASC),
  CONSTRAINT `fk_aluno_pessoa`
    FOREIGN KEY (`codpessoa`)
    REFERENCES `smasy_pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_pessoa_respo`
    FOREIGN KEY (`responsavel`)
    REFERENCES `smasy_pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_professor` ;

CREATE TABLE IF NOT EXISTS `smasy_professor` (
  `codprof` INT NOT NULL AUTO_INCREMENT,
  `codpessoa` INT NOT NULL,
  `valoraula` DOUBLE NULL,
  `reccreatedby` INT NOT NULL,
  `reccreatedon` DATETIME NOT NULL,
  `recmodifiedby` INT NULL,
  `recmodifiedon` DATETIME NULL,
  PRIMARY KEY (`codprof`),
  INDEX `fk_professor_pessoa_idx` (`codpessoa` ASC),
  CONSTRAINT `fk_professor_pessoa`
    FOREIGN KEY (`codpessoa`)
    REFERENCES `smasy_pessoa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_sala` ;

CREATE TABLE IF NOT EXISTS `smasy_sala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `capacidade` INT NULL,
  `reccreatedby` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_horario` ;

CREATE TABLE IF NOT EXISTS `smasy_horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `horaini` TIME NULL,
  `horafim` TIME NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_faixaetaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_faixaetaria` ;

CREATE TABLE IF NOT EXISTS `smasy_faixaetaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idadeini` INT NULL,
  `idadefim` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_modalidade` ;

CREATE TABLE IF NOT EXISTS `smasy_modalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `codfaixaetaria` INT NULL,
  `reccreatedby` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modalidade_faixaetaria_idx` (`codfaixaetaria` ASC),
  CONSTRAINT `fk_modalidade_faixaetaria`
    FOREIGN KEY (`codfaixaetaria`)
    REFERENCES `smasy_faixaetaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_turma` ;

CREATE TABLE IF NOT EXISTS `smasy_turma` (
  `codturma` VARCHAR(50) NOT NULL,
  `codsala` INT NULL,
  `nome` VARCHAR(45) NULL,
  `maxalunos` INT NULL,
  `dtinicial` DATE NULL,
  `dtfinal` DATE NULL,
  `codhorario` INT NULL,
  `codmodalidade` INT NULL,
  `reccreatedby` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`codturma`),
  INDEX `fk_turma_sala_idx` (`codsala` ASC),
  INDEX `fk_turma_horario_idx` (`codhorario` ASC),
  INDEX `fk_turma_modalidade_idx` (`codmodalidade` ASC),
  CONSTRAINT `fk_turma_sala`
    FOREIGN KEY (`codsala`)
    REFERENCES `smasy_sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_horario`
    FOREIGN KEY (`codhorario`)
    REFERENCES `smasy_horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_modalidade`
    FOREIGN KEY (`codmodalidade`)
    REFERENCES `smasy_modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_formapgto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_formapgto` ;

CREATE TABLE IF NOT EXISTS `smasy_formapgto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `desconto` DOUBLE NULL,
  `tipodesconto` INT NULL,
  `parcelas` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_matriculaaluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_matriculaaluno` ;

CREATE TABLE IF NOT EXISTS `smasy_matriculaaluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codturma` VARCHAR(50) NULL,
  `ra` INT NULL,
  `formapgto` INT NULL,
  `dtmatricula` DATE NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matric_aluno_idx` (`ra` ASC),
  INDEX `fk_matric_turma_idx` (`codturma` ASC),
  INDEX `fk_matric_pgto_idx` (`formapgto` ASC),
  CONSTRAINT `fk_matric_aluno`
    FOREIGN KEY (`ra`)
    REFERENCES `smasy_aluno` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matric_turma`
    FOREIGN KEY (`codturma`)
    REFERENCES `smasy_turma` (`codturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matric_pgto`
    FOREIGN KEY (`formapgto`)
    REFERENCES `smasy_formapgto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smasy_turmaprof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smasy_turmaprof` ;

CREATE TABLE IF NOT EXISTS `smasy_turmaprof` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codprof` INT NULL,
  `codturma` VARCHAR(50) NULL,
  `tipoprof` INT NULL,
  `reccreateddon` DATETIME NULL,
  `recmodifiedby` INT NULL,
  `recmodifieddon` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turmaprof_prof_idx` (`codprof` ASC),
  INDEX `fk_turmaprof_turma_idx` (`codturma` ASC),
  CONSTRAINT `fk_turmaprof_prof`
    FOREIGN KEY (`codprof`)
    REFERENCES `smasy_professor` (`codprof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmaprof_turma`
    FOREIGN KEY (`codturma`)
    REFERENCES `smasy_turma` (`codturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
